function s=tex_system_tables(filename1,filename2,filename3,filename4)
%% Copyright (C) 2013, Bruce Minaker
%% This file is intended for use with Octave.
%% tex_system_tables.m is free software; you can redistribute it and/or modify it
%% under the terms of the GNU General Public License as published by
%% the Free Software Foundation; either version 2, or (at your option)
%% any later version.
%%
%% tex_system_tables.m is distributed in the hope that it will be useful, but
%% WITHOUT ANY WARRANTY; without even the implied warranty of
%% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
%% General Public License for more details at www.gnu.org/copyleft/gpl.html.
%%
%%--------------------------------------------------------------------

%% This function writes a tex file describing the system

s=['\\section{System Description}\n'];

%	'\\multicolumn{6}{c}{Inertia ($I_{\\textrm{xx}}$, $I_{\\textrm{yy}}$, $I_{\\textrm{zz}}$ [kg$\\cdot$m$^2$])} &\n' ...
%	'\\multicolumn{6}{c}{Inertia ($I_{\\textrm{xy}}$, $I_{\\textrm{yz}}$, $I_{\\textrm{zx}}$ [kg$\\cdot$m$^2$])}\\\\},\n' ...

s=[s 'The properties of the bodies are given in Tables~\\ref{bodycoords}~and~\\ref{bodyinertia}.\n'];
s=[s 'The properties of the connections are given in Tables~\\ref{pointcoords},~\\ref{linecoords},~and~\\ref{connectcoords}.\n'];

s=[s '\\begin{center}\n' ...
	'\\begin{footnotesize}\n' ...
	'\\pgfplotstabletypeset[%%\n' ...
	'begin table=\\begin{longtable},\n' ...
	'end table=\\end{longtable},\n' ...
	'every head row/.style={output empty row,\n' ...
	'before row={\\caption{Body CG Locations and Mass}\\label{bodycoords}\\\\\n' ...
	'\\toprule No. & Body Name &\n' ...
	'\\multicolumn{6}{c}{Location [m]} &\n' ...
	'\\multicolumn{2}{c}{Mass [kg]}\\\\},\n' ...
	'after row=\\midrule},\n' ...
	'columns={num,name,rx,ry,rz,mass}]{' filename1 '}\n' ...
	'\\end{footnotesize}\n' ...
	'\\end{center}\n'];

s=[s '\\begin{center}\n' ...
	'\\begin{footnotesize}\n' ...
	'\\pgfplotstabletypeset[%%\n' ...
	'begin table=\\begin{longtable},\n' ...
	'end table=\\end{longtable},\n' ...
	'every head row/.style={output empty row,\n' ...
	'before row={\\caption{Body Inertia Properties}\\label{bodyinertia}\\\\\n' ...
	'\\toprule No. & Body Name &\n' ...
	'\\multicolumn{12}{c}{Inertia$^\\dagger$ [\\si{\\kg.\\m^2}] ($I_\\text{xx}$, $I_\\text{yy}$, $I_\\text{zz}$; $I_\\text{xy}$, $I_\\text{yz}$, $I_\\text{zx}$)}\\\\},\n' ...
	'after row=\\midrule},\n' ...
	'every last row/.style={after row=\\bottomrule \\multicolumn{14}{l}{$^\\dagger$Inertias are defined as the positive integral over the body.}\\\\ \\multicolumn{14}{l}{For example, $I_{\\text{xy}}=+\\! \\int \\! r_\\text{x}r_\\text{y} \\,\\text{d}m $.}},\n' ...
	'columns={num,name,ixx,iyy,izz,ixy,iyz,ixz}]{' filename1 '}\n' ...
	'\\end{footnotesize}\n' ...
	'\\end{center}\n'];

s=[s '\\begin{center}\n' ...
	'\\begin{footnotesize}\n' ...
	'\\pgfplotstabletypeset[%%\n' ...
	'begin table=\\begin{longtable},\n' ...
	'end table=\\end{longtable},\n' ...
	'every head row/.style={output empty row,\n' ...
	'before row={\\caption{Connection Location and Direction}\\label{pointcoords}\\\\\n' ...
	'\\toprule No. & Connection Name &\n' ...
	'\\multicolumn{6}{c}{Location [m]} & \\multicolumn{6}{c}{Unit Axis}\\\\},\n' ...
	'after row=\\midrule}]{' filename2 '}\n' ...
	'\\end{footnotesize}\n' ...
	'\\end{center}\n'];

s=[s '\\begin{center}\n' ...
	'\\begin{footnotesize}\n' ...
	'\\pgfplotstabletypeset[%%\n' ...
	'begin table=\\begin{longtable},\n' ...
	'end table=\\end{longtable},\n' ...
	'every head row/.style={output empty row,\n' ...
	'before row={\\caption{Connection Locations}\\label{linecoords}\\\\\n' ...
	'\\toprule No. & Connection Name &\n' ...
	'\\multicolumn{6}{c}{Location [m]} & \\multicolumn{6}{c}{Location [m]}\\\\},\n' ...
	'after row=\\midrule}]{' filename3 '}\n' ...
	'\\end{footnotesize}\n' ...
	'\\end{center}\n'];

s=[s '\\begin{center}\n' ...
	'\\begin{footnotesize}\n' ...
	'\\pgfplotstabletypeset[%%\n' ...
	'begin table=\\begin{longtable},\n' ...
	'end table=\\end{longtable},\n' ...
	'every head row/.style={output empty row,\n' ...
	'before row={\\caption{Connection Properties}\\label{connectcoords}\\\\\n' ...
	'\\toprule No. & Connection Name &\n' ...
	'\\multicolumn{1}{c}{Stiffness [\\si{\\N/\\m}]} & \\multicolumn{1}{c}{Damping [\\si{\\N\\s/\\m}]}\\\\},\n' ...
	'after row=\\midrule}, columns={num,name,stiffness,damping}]{' filename4 '}\n' ...
	'\\end{footnotesize}\n' ...
	'\\end{center}\n'];


end %% Leave

%  s=[s '\\begin{table}[ht]\n' ...
%  	'\\begin{center}\n' ...
%  	'\\begin{threeparttable}\n' ...
%  	'\\begin{footnotesize}\n' ...
%  	'\\caption{Connection Location and Properties}\n' ...
%  	'\\label{connectcoords}\n' ...
%  	'\\pgfplotstabletypeset[%%\n' ...
%  	'every head row/.style={output empty row, before row={\\toprule No. & Connection Name &\n' ...
%  	'\\multicolumn{6}{c}{Location [m]} & \\multicolumn{6}{c}{Unit Axis} & \\multicolumn{1}{c}{Stiffness [N/m]} & \\multicolumn{1}{c}{Damping [Ns/m]}\\\\},\n' ...
%  	'after row=\\midrule}, columns={num,name,rx,ry,rz,ux,uy,uz,stiffness,damping}]{' filename2 '}\n' ...
%  	'\\end{footnotesize}\n' ...
%  	'\\end{threeparttable}\n' ...
%  	'\\end{center}\n' ...
%  	'\\end{table}\n'];

