function s=tex_eqn(name,matrix,filename)
%% Copyright (C) 2008, Bruce Minaker
%% This file is intended for use with Octave.
%% make_tex.m is free software; you can redistribute it and/or modify it
%% under the terms of the GNU General Public License as published by
%% the Free Software Foundation; either version 2, or (at your option)
%% any later version.
%%
%% make_tex.m is distributed in the hope that it will be useful, but
%% WITHOUT ANY WARRANTY; without even the implied warranty of
%% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
%% General Public License for more details at www.gnu.org/copyleft/gpl.html.
%%
%%--------------------------------------------------------------------

[n,m]=size(matrix);

s='';
t='\\begin{footnotesize}\n';
u='\\end{footnotesize}\n';

if(m>6||n>6)

s=[s '\\begin{footnotesize}\n' ...
		'\\begin{center}\n'];

s=[s '\\pgfplotstabletypeset[\n' ...
	'begin table=\\begin{longtable},\n' ...
	'end table=\\end{longtable},\n' ...
	'columns={[index]0,[index]1,[index]2,[index]0,[index]1,[index]2},\n' ...
	'display columns/0/.style={select equal part entry of={0}{2}},\n' ...
	'display columns/1/.style={select equal part entry of={0}{2}},\n' ...
	'display columns/2/.style={select equal part entry of={0}{2}},\n' ...
	'display columns/3/.style={select equal part entry of={1}{2}},\n' ...
	'display columns/4/.style={select equal part entry of={1}{2}},\n' ...
	'display columns/5/.style={select equal part entry of={1}{2}},\n' ...
	'columns/0/.style={int detect, column type=c,column name={Row}},\n' ...
	'columns/1/.style={int detect, column type=c,column name={Column}},\n' ...
	'columns/2/.style={sci,sci zerofill,precision=8,dec sep align,column name={Value}}]\n' ...
	'{unformatted/' filename '}\n'];

	s=[s '\\end{center}\n' ...
		'\\end{footnotesize}\n'];

elseif(n>0&&m>0)

s=['\\pgfplotstabletypeset[\n' ...
	'every head row/.style={output empty row},\n' ...
	'every last row/.style={after row={}},\n'];
	for i=1:n
		s=[s 'columns/' num2str(i-1) '/.style={sci,sci zerofill,precision=6,dec sep align},\n'];
	end
s=[s 'write to macro=\\' name ',\n' ...
	'typeset=false]\n' ...
	'{unformatted/' filename '}\n'];
	
s=[s t '\\[\n' ...
	'\\mathbf{' name '}=\n' ...
	'\\left[\\!\\!\n' ...
	'\\' name '\n' ...
	'\\right]\n' ...
	'\\]\n' ...
	u ];

end

end  %% Leave






%  elseif(n>0&&m>0)
%  	for j=1:n
%  		for k=1:m-1
%  			s=[s sprintf('\\\\pgfmathprintnumber{ %#5.5e }& ',matrix(j,k))];
%  		end
%  		s=[s sprintf('\\\\pgfmathprintnumber{ %#5.5e }\\\\\\\\\n', matrix(j,m))];
%  	end
%  	
%  	s=['\\pgfkeys{/pgf/number format/.cd,sci,sci zerofill,precision=4}\n' ...
%  		t '\\[\n' ...
%  		'\\mathbf{ ' name '}=\n' ...
%  		'\\begin{bmatrix}\n' ...
%  		s ...
%  		'\\end{bmatrix}\n' ...
%  		'\\]\n' ...
%  		u ];
%  end









%  	s=['\\begin{footnotesize}\n' ...
%  		'\\begin{center}\n' ...
%  		'\\begin{longtable}{ccN[3]{1}{5}|ccN[3]{1}{5}|ccN[3]{1}{5}|ccN[3]{1}{5}}\n' ...
%  		'\\toprule\n' ...
%  		'Row & Column & \\multicolumn{1}{c}{Value} & Row & Column & \\multicolumn{1}{c}{Value} & Row & Column & \\multicolumn{1}{c}{Value} & Row & Column & \\multicolumn{1}{c}{Value}\\\\\n' ...
%  		'\\midrule\n'];
%  	c=4;
%  	for j=1:n
%  		for k=1:m
%  			if(abs(matrix(j,k))>0)
%  				s=[s sprintf('%i & %i & %#5.5e', j,k,matrix(j,k))];
%  				c=c-1;
%  				if(c==0)
%  					s=[s '\\\\\n'];
%  					c=4;
%  				else
%  					s=[s ' & '];
%  				end
%  			end
%  		end
%  	end
%  	if(c<4)
%  		for j=1:c-1
%  			s=[s '& & & '];
%  		end
%  		s=[s '& &\\\\\n'];
%  	end
%  	s=[s '\\bottomrule\n' ...
%  		'\\end{longtable}\n' ...
%  		'\\end{center}\n' ...
%  		'\\end{footnotesize}\n'];
