function s=tex_bode3_pgfplot(filename,in,out)
%% Copyright (C) 2009, Bruce Minaker
%% This file is intended for use with Octave.
%% tex_bode_pgfplot.m is free software; you can redistribute it and/or modify it
%% under the terms of the GNU General Public License as published by
%% the Free Software Foundation; either version 2, or (at your option)
%% any later version.
%%
%% tex_bode_pgfplot.m is distributed in the hope that it will be useful, but
%% WITHOUT ANY WARRANTY; without even the implied warranty of
%% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
%% General Public License for more details at www.gnu.org/copyleft/gpl.html.
%%
%%--------------------------------------------------------------------

nin=length(in);
nout=length(out);
s='\\section{Frequency Response Plots}\n';

for i=1:nin  %% For each input-output pair
	for j=1:nout
		s=[s '\\begin{figure}[hbtp]\n' ...
		'\\begin{center}\n' ...
		'\\begin{footnotesize}\n' ...
		'\\pgfplotsset{colormap={windsor}{color=(gray) color=(white) color=(gray)}}\n' ...
		'\\pgfplotsset{tick label style={font=\\scriptsize},label style={font=\\scriptsize},title style={font=\\small},xminorticks={false}}\n' ...
		'\\begin{tikzpicture}\n' ...
		'\\begin{semilogxaxis}[height=3in,width=4in,tick style={thin,black},view={45}{45},xlabel={Frequency [Hz]},ylabel={Speed [m/s]},zlabel={Transfer Function [dB]},enlargelimits=false,xlabel style={sloped like x axis}, ylabel style={sloped like y axis}]\n' ...
		'\\addplot3[surf] table[x=frequency,y=speed,z=m' num2str((i-1)*nout+j) ']{' filename '};\n' ...
		'\\end{semilogxaxis}\n' ...
		'\\end{tikzpicture}\n' ...
		'\\end{footnotesize}\n' ...
		'\\caption{Frequency response: ' out{j} '/' in{i} '}\n' ...
		'\\label{bode_plot_' num2str((i-1)*nout+j) '}\n' ...
		'\\end{center}\n' ...
		'\\end{figure}\n\n'];
	end
end
s=[s '\\clearpage\n\n'];

end  %% Leave

