function s=tex_lambda_defln(result,filename1,filename2)

%% GPL here
%	'\\begin{tablenotes}\n' ...
%	'\\item All values in standard metric units, i.e., [m].\n' ...
%	'\\end{tablenotes}\n' ...

s='\\section{Equilibrium Analysis}\n';

s=[s 'The results of the equilibrium load analysis are given in Tables~\\ref{deflns}~and~\\ref{preloads}.\n'];

s=[s '\\begin{center}\n' ...
	'\\begin{footnotesize}\n' ...
	'\\pgfplotstabletypeset[\n' ...
	'begin table=\\begin{longtable},\n' ...
	'end table=\\end{longtable},\n' ...
	'every head row/.style={output empty row,\n' ...
	'before row={\\caption{System Static Deflections}\\label{deflns}\\\\\n' ...
	'\\toprule No. & Body Name & Type &\n' ...
	'\\multicolumn{6}{c}{Deflection [m] or [rad]}\\\\},\n' ...
	'after row=\\midrule}]{' filename1 '}\n' ...
	'\\end{footnotesize}\n' ...
	'\\end{center}\n'];

s=[s '\\begin{center}\n' ...
	'\\begin{footnotesize}\n' ...
	'\\pgfplotstabletypeset[\n' ...
	'begin table=\\begin{longtable},\n' ...
	'end table=\\end{longtable},\n' ...
	'every head row/.style={output empty row,\n' ...
	'before row={\\caption{System Preloads}\\label{preloads}\\\\\n' ...
	'\\toprule No. & Connector Name & Type &\n' ...
	'\\multicolumn{8}{c}{Load [N] or [Nm] (Components; Magnitude)}\\\\},\n' ...
	'after row=\\midrule}]{' filename2 '}\n' ...
	'\\end{footnotesize}\n' ...
	'\\end{center}\n'];

end %% Return

