function s=tex_eig_pgftable(filename1,filename2)
%% Copyright (C) 2003, 2008 Bruce Minaker
%% This file is intended for use with Octave.
%% tex_eig_table.m is free software; you can redistribute it and/or modify it
%% under the terms of the GNU General Public License as published by
%% the Free Software Foundation; either version 2, or (at your option)
%% any later version.
%%
%% tex_eig_table.m is distributed in the hope that it will be useful, but
%% WITHOUT ANY WARRANTY; without even the implied warranty of
%% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
%% General Public License for more details at www.gnu.org/copyleft/gpl.html.
%%
%%--------------------------------------------------------------------

s='\\section{Eigenvalue Analysis}\n';

s=[s 'The eigenvalue properties are given in Tables~\\ref{evals}~and~\\ref{evals-b}.\n\n'];

s=[s '\\begin{center}\n' ...
	'\\begin{footnotesize}\n' ...
	'\\pgfplotstabletypeset[%%\n' ...
	'begin table=\\begin{longtable},\n' ...
	'end table=\\end{longtable},\n' ...
	'every head row/.style={\n' ...
	'before row={\\caption{Eigenvalues}\\label{evals}\\\\ \\toprule},\n' ...
	'after row=\\midrule},\n' ...
	'every last row/.style={\n' ...
	'after row=\\bottomrule \\multicolumn{9}{l}{Note: oscillatory roots appear as complex conjugates.}},\n' ...
	'columns={num,real,imag,realhz,imaghz}]{' filename1 '}\n' ...
	'\\end{footnotesize}\n' ...
	'\\end{center}\n'];


%% New table

s=[s '\\begin{center}\n' ...
	'\\begin{footnotesize}\n' ...
	'\\pgfplotstabletypeset[%%\n' ...
	'begin table=\\begin{longtable},\n' ...
	'end table=\\end{longtable},\n' ...
	'every head row/.style={\n' ...
	'before row={\\caption{Eigenvalue Analysis}\\label{evals-b}\\\\ \\toprule},\n' ...
	'after row=\\midrule},\n' ...
	'every last row/.style={\n' ...
	'after row=\\bottomrule \\multicolumn{9}{l}{Notes: a) oscillatory roots are listed twice, b) negative time constants denote unstable roots.}},\n' ...
	'columns={num,nfreq,zeta,tau,lambda}]{' filename2 '}\n' ...
	'\\end{footnotesize}\n' ...
	'\\end{center}\n'];

end  %% Leave
