function [s1,s2]=vrml_motion(time,lcn,rtn,scl,grp,x3d)
%% Copyright (C) 2011, Bruce Minaker
%% This file is intended for use with Octave.
%% vrml_motion.m is free software; you can redistribute it and/or modify it
%% under the terms of the GNU General Public License as published by
%% the Free Software Foundation; either version 2, or (at your option)
%% any later version.
%%
%% vrml_motion.m is distributed in the hope that it will be useful, but
%% WITHOUT ANY WARRANTY; without even the implied warranty of
%% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
%% General Public License for more details at www.gnu.org/copyleft/gpl.html.
%%
%%--------------------------------------------------------------------

pstn=sprintf('%f %f %f,\n',lcn);
pstn=pstn(1:end-2);

rntn=sprintf('%f %f %f %f,\n',rtn);
rntn=rntn(1:end-2);

scal=sprintf('%f %f %f,\n',scl);
scal=scal(1:end-2);

tme=sprintf('%f,',time);
tme=tme(1:end-2);

s1=['DEF ID' grp ' Transform {\n' ...
	'  children [ ' ...
	x3d ...
	'DEF IDt' grp ' PositionInterpolator {\n' ...
	'keyValue [\n' pstn '\n]\n' ...
	'key [ ' tme ' ]\n' ...
	'}\n' ...
	'DEF IDr' grp ' OrientationInterpolator {\n' ...
	'keyValue [\n' rntn '\n]\n' ...
	'key [ ' tme ' ]\n' ...
	'}\n' ...
	']}\n' ...
	];
%  	'DEF IDs' grp ' PositionInterpolator {\n' ...
%  	'keyValue [\n' scal '\n]\n' ...
%  	'key [ ' tme ' ]\n' ...
%  	'}\n' ...
	
	
s2=[
	'ROUTE IDtimer.fraction_changed TO IDt' grp '.set_fraction\n' ...
	'ROUTE IDtimer.fraction_changed TO IDr' grp '.set_fraction\n' ...
	'ROUTE IDt' grp '.value_changed TO ID' grp '.set_translation\n' ...
	'ROUTE IDr' grp '.value_changed TO ID' grp '.set_rotation\n' ...
	];
end

%  	'ROUTE IDtimer.fraction_changed TO IDs' grp '.set_fraction\n' ...
%  	'ROUTE IDs' grp '.value_changed TO ID' grp '.set_scale\n' ...
